
#데이터 합치기
강남구 <- left_join (sub_gnam,shin_강남구,by="기준년월")
강동구 <- left_join (sub_gangdong,shin_강동구,by="기준년월")
강북구 <- left_join (sub_kbook,shin_강북구,by="기준년월")
강서구 <- left_join (sub_gangseo,shin_강서구,by="기준년월")
관악구 <- left_join (sub_kwan,shin_관악구,by="기준년월")
광진구 <- left_join (sub_kwang,shin_광진구,by="기준년월")
구로구 <- left_join (sub_guro,shin_구로구,by="기준년월")
금천구 <- left_join (sub_keum,shin_금천구,by="기준년월")
노원구 <- left_join (sub_noone,shin_노원구,by="기준년월")
도봉구 <- left_join (sub_dobong,shin_도봉구,by="기준년월")
동대문구 <- left_join (sub_moon,shin_동대문구,by="기준년월")
동작구 <- left_join (sub_djak,shin_동작구,by="기준년월")
마포구 <- left_join (sub_mapo,shin_마포구,by="기준년월")
서대문구 <- left_join (sub_seo,shin_서대문구,by="기준년월")
서초구 <- left_join (sub_scho,shin_서초구,by="기준년월")
성동구 <- left_join (sub_sdong,shin_성동구,by="기준년월")
성북구 <- left_join (sub_seong,shin_성북구,by="기준년월")
송파구 <- left_join (sub_song,shin_송파구,by="기준년월")
양천구 <- left_join (sub_yang,shin_양천구,by="기준년월")
영등포구 <- left_join (sub_yung,shin_영등포구,by="기준년월")
용산구 <- left_join (sub_yong,shin_용산구,by="기준년월")
은평구 <- left_join (sub_eun,shin_은평구,by="기준년월")
종로구 <- left_join (sub_jong,shin_종로구,by="기준년월")
중구 <- left_join (sub_jung,shin_중구,by="기준년월")
중랑구 <- left_join (sub_jlang,shin_중랑구,by="기준년월")

#숫자->문자
강남구$기준년월<-as.character(강남구$기준년월)
강동구$기준년월<-as.character(강동구$기준년월)
강북구$기준년월<-as.character(강북구$기준년월)
강서구$기준년월<-as.character(강서구$기준년월)
관악구$기준년월<-as.character(관악구$기준년월)
광진구$기준년월<-as.character(광진구$기준년월)
구로구$기준년월<-as.character(구로구$기준년월)
금천구$기준년월<-as.character(금천구$기준년월)
노원구$기준년월<-as.character(노원구$기준년월)
도봉구$기준년월<-as.character(도봉구$기준년월)
동대문구$기준년월<-as.character(동대문구$기준년월)
동작구$기준년월<-as.character(동작구$기준년월)
마포구$기준년월<-as.character(마포구$기준년월)
서대문구$기준년월<-as.character(서대문구$기준년월)
서초구$기준년월<-as.character(서초구$기준년월)
성동구$기준년월<-as.character(성동구$기준년월)
성북구$기준년월<-as.character(성북구$기준년월)
송파구$기준년월<-as.character(송파구$기준년월)
양천구$기준년월<-as.character(양천구$기준년월)
영등포구$기준년월<-as.character(영등포구$기준년월)
용산구$기준년월<-as.character(용산구$기준년월)
은평구$기준년월<-as.character(은평구$기준년월)
종로구$기준년월<-as.character(종로구$기준년월)
중구$기준년월<-as.character(중구$기준년월)
중랑구$기준년월<-as.character(중랑구$기준년월)

