nstall.packages("dplyr")
library(dplyr)
install.packages("ggplot2")
library(ggplot2)
install.packages("UsingR")
library(UsingR)
install.packages("readxl")
library(readxl)
install.packages("psych")
library(psych)
install.packages("plyr")
library(plyr)

#데이터 불러오기
shin <- readxl::read_excel(path="C:/data_fi/금융대회_신한은행.xlsx",
                           sheet = "finance_data",
                           col_names=TRUE)

dim(shin)
dim(shin[complete.cases(shin),])
head(shin)


#중복값확인
duplicates <- s %>% duplicated() %>% table()
duplicates

#결측값확인
table(is.na(s$가맹점매출입금))
table(is.na(s$지역구))
table(is.na(s$기준년월))
table(is.na(s$총소비금액))
table(is.na(s$총수신금액))


#필요한 데이터 추출

shin <- shin %>% filter(가맹점매출입금!=0) %>% dplyr::select(기준년월, 지역구, 총소비금액, 총수신금액)
head(shin)
summary(shin)

#데이터 요약 및 상자그림
summary(shin$대출총합)
summary(shin$가맹점매출입금)
boxplot(shin$대출총합)
boxplot(shin$가맹점매출입금)


#기준년월로 나누기
shin_강남구 <- shin %>% filter(지역구=="강남구")
shin_강동구 <- shin %>% filter(지역구=="강동구")
shin_강북구 <- shin %>% filter(지역구=="강북구")
shin_강서구 <- shin %>% filter(지역구=="강서구")
shin_관악구 <- shin %>% filter(지역구=="관악구")
shin_광진구 <- shin %>% filter(지역구=="광진구")
shin_구로구 <- shin %>% filter(지역구=="구로구")
shin_금천구 <- shin %>% filter(지역구=="금천구")
shin_노원구 <- shin %>% filter(지역구=="노원구")
shin_도봉구 <- shin %>% filter(지역구=="도봉구")
shin_동대문구 <- shin %>% filter(지역구=="동대문구")
shin_동작구 <- shin %>% filter(지역구=="동작구")
shin_마포구 <- shin %>% filter(지역구=="마포구")
shin_서대문구 <- shin %>% filter(지역구=="서대문구")
shin_서초구 <- shin %>% filter(지역구=="서초구")
shin_성동구 <- shin %>% filter(지역구=="성동구")
shin_성북구 <- shin %>% filter(지역구=="성북구")
shin_송파구 <- shin %>% filter(지역구=="송파구")
shin_양천구 <- shin %>% filter(지역구=="양천구")
shin_영등포구 <- shin %>% filter(지역구=="영등포구")
shin_용산구 <- shin %>% filter(지역구=="용산구")
shin_은평구 <- shin %>% filter(지역구=="은평구")
shin_종로구 <- shin %>% filter(지역구=="종로구")
shin_중구 <- shin %>% filter(지역구=="중구")
shin_중랑구 <- shin %>% filter(지역구=="중랑구")



shin_강남구 <- ddply(shin_강남구, .(기준년월), summarise, avg소비 = mean(총소비금액), avg수신 = mean(총수신금액)) 
shin_강동구 <- ddply(shin_강동구, .(기준년월), summarise, avg소비 = mean(총소비금액), avg수신 = mean(총수신금액)) 
shin_강북구 <- ddply(shin_강북구, .(기준년월), summarise, avg소비 = mean(총소비금액), avg수신 = mean(총수신금액)) 
shin_강서구 <- ddply(shin_강서구, .(기준년월), summarise, avg소비 = mean(총소비금액), avg수신 = mean(총수신금액)) 
shin_관악구 <- ddply(shin_관악구, .(기준년월), summarise, avg소비 = mean(총소비금액), avg수신 = mean(총수신금액))
shin_광진구 <- ddply(shin_광진구, .(기준년월), summarise, avg소비 = mean(총소비금액), avg수신 = mean(총수신금액)) 
shin_구로구 <- ddply(shin_구로구, .(기준년월), summarise, avg소비 = mean(총소비금액), avg수신 = mean(총수신금액)) 
shin_금천구 <- ddply(shin_금천구, .(기준년월), summarise, avg소비 = mean(총소비금액), avg수신 = mean(총수신금액)) 
shin_노원구 <- ddply(shin_노원구, .(기준년월), summarise, avg소비 = mean(총소비금액), avg수신 = mean(총수신금액)) 
shin_도봉구 <- ddply(shin_도봉구, .(기준년월), summarise, avg소비 = mean(총소비금액), avg수신 = mean(총수신금액)) 
shin_동대문구 <- ddply(shin_동대문구, .(기준년월), summarise, avg소비 = mean(총소비금액), avg수신 = mean(총수신금액)) 
shin_동작구 <- ddply(shin_동작구, .(기준년월), summarise, avg소비 = mean(총소비금액), avg수신 = mean(총수신금액)) 
shin_마포구 <- ddply(shin_마포구, .(기준년월), summarise, avg소비 = mean(총소비금액), avg수신 = mean(총수신금액)) 
shin_서대문구 <- ddply(shin_서대문구, .(기준년월), summarise, avg소비 = mean(총소비금액), avg수신 = mean(총수신금액)) 
shin_서초구 <- ddply(shin_서초구, .(기준년월), summarise, avg소비 = mean(총소비금액), avg수신 = mean(총수신금액)) 
shin_성동구 <- ddply(shin_성동구, .(기준년월), summarise, avg소비 = mean(총소비금액), avg수신 = mean(총수신금액)) 
shin_성북구 <- ddply(shin_성북구, .(기준년월), summarise, avg소비 = mean(총소비금액), avg수신 = mean(총수신금액)) 
shin_송파구 <- ddply(shin_송파구, .(기준년월), summarise, avg소비 = mean(총소비금액), avg수신 = mean(총수신금액)) 
shin_양천구 <- ddply(shin_양천구, .(기준년월), summarise, avg소비 = mean(총소비금액), avg수신 = mean(총수신금액)) 
shin_영등포구 <- ddply(shin_영등포구, .(기준년월), summarise, avg소비 = mean(총소비금액), avg수신 = mean(총수신금액)) 
shin_용산구 <- ddply(shin_용산구, .(기준년월), summarise, avg소비 = mean(총소비금액), avg수신 = mean(총수신금액)) 
shin_은평구 <- ddply(shin_은평구, .(기준년월), summarise, avg소비 = mean(총소비금액), avg수신 = mean(총수신금액)) 
shin_종로구 <- ddply(shin_종로구, .(기준년월), summarise, avg소비 = mean(총소비금액), avg수신 = mean(총수신금액)) 
shin_중구 <- ddply(shin_중구, .(기준년월), summarise, avg소비 = mean(총소비금액), avg수신 = mean(총수신금액)) 
shin_중랑구 <- ddply(shin_중랑구, .(기준년월), summarise, avg소비 = mean(총소비금액), avg수신 = mean(총수신금액)) 

par(mfrow=c(1,1))
barplot(cbind(avg소비,avg수신)~기준년월,shin_강남구,beside=T,main="강남구",xlab="기준년월",ylab="소비, 수신")
barplot(cbind(avg소비,avg수신)~기준년월,shin_강동구,beside=T,main="강동구",xlab="기준년월",ylab="소비, 수신")
barplot(cbind(avg소비,avg수신)~기준년월,shin_강북구,beside=T,main="강북구",xlab="기준년월",ylab="소비, 수신")
barplot(cbind(avg소비,avg수신)~기준년월,shin_강서구,beside=T,main="강서구",xlab="기준년월",ylab="소비, 수신")
barplot(cbind(avg소비,avg수신)~기준년월,shin_관악구,beside=T,main="관악구",xlab="기준년월",ylab="소비, 수신")
barplot(cbind(avg소비,avg수신)~기준년월,shin_광진구,beside=T,main="광진구",xlab="기준년월",ylab="소비, 수신")
barplot(cbind(avg소비,avg수신)~기준년월,shin_구로구,beside=T,main="구로구",xlab="기준년월",ylab="소비, 수신")
barplot(cbind(avg소비,avg수신)~기준년월,shin_금천구,beside=T,main="금천구",xlab="기준년월",ylab="소비, 수신")
barplot(cbind(avg소비,avg수신)~기준년월,shin_노원구,beside=T,main="노원구",xlab="기준년월",ylab="소비, 수신")
barplot(cbind(avg소비,avg수신)~기준년월,shin_도봉구,beside=T,main="도봉구",xlab="기준년월",ylab="소비, 수신")
barplot(cbind(avg소비,avg수신)~기준년월,shin_동대문구,beside=T,main="동대문구",xlab="기준년월",ylab="소비, 수신")
barplot(cbind(avg소비,avg수신)~기준년월,shin_동작구,beside=T,main="동작구",xlab="기준년월",ylab="소비, 수신")
barplot(cbind(avg소비,avg수신)~기준년월,shin_마포구,beside=T,main="마포구",xlab="기준년월",ylab="소비, 수신")
barplot(cbind(avg소비,avg수신)~기준년월,shin_서대문구,beside=T,main="서대문구",xlab="기준년월",ylab="소비, 수신")
barplot(cbind(avg소비,avg수신)~기준년월,shin_서초구,beside=T,main="서초구",xlab="기준년월",ylab="소비, 수신")
barplot(cbind(avg소비,avg수신)~기준년월,shin_성동구,beside=T,main="성동구",xlab="기준년월",ylab="소비, 수신")
barplot(cbind(avg소비,avg수신)~기준년월,shin_성북구,beside=T,main="성북구",xlab="기준년월",ylab="소비, 수신")
barplot(cbind(avg소비,avg수신)~기준년월,shin_송파구,beside=T,main="송파구",xlab="기준년월",ylab="소비, 수신")
barplot(cbind(avg소비,avg수신)~기준년월,shin_양천구,beside=T,main="양천구",xlab="기준년월",ylab="소비, 수신")
barplot(cbind(avg소비,avg수신)~기준년월,shin_영등포구,beside=T,main="영등포구",xlab="기준년월",ylab="소비, 수신")
barplot(cbind(avg소비,avg수신)~기준년월,shin_용산구,beside=T,main="용산구",xlab="기준년월",ylab="소비, 수신")
barplot(cbind(avg소비,avg수신)~기준년월,shin_은평구,beside=T,main="은평구",xlab="기준년월",ylab="소비, 수신")
barplot(cbind(avg소비,avg수신)~기준년월,shin_종로구,beside=T,main="종로구",xlab="기준년월",ylab="소비, 수신")
barplot(cbind(avg소비,avg수신)~기준년월,shin_중구,beside=T,main="중구",xlab="기준년월",ylab="소비, 수신")
barplot(cbind(avg소비,avg수신)~기준년월,shin_중랑구,beside=T,main="중랑구",xlab="기준년월",ylab="소비, 수신")
